senzing-garage/sz-sdk-python-grpc

- CHANGELOG.md
- README.md
- setup.cfg
> 3.dockter.5

- CHANGELOG.md
- README.md
- examples/misc/add_truthset_data.py
- examples/misc/add_truthset_datasources.py
- setup.cfg
> 3.dockter.7

- setup.cfg
> #19 Update release number

- docs/development.md
- docs/source/senzing.rst
- setup.cfg
> 3.dockter.9

- .github/linters/.yaml-lint.yml
- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
- .github/workflows/build-distribution.yaml
- .github/workflows/create-sphinx-documentation.yaml
- .github/workflows/dependabot-approve-and-merge.yaml
- .github/workflows/flake8.yaml
- .github/workflows/isort.yaml
- .github/workflows/lint-workflows.yaml
- .github/workflows/publish-to-pypi.yaml
- .github/workflows/pylint.yaml
- .github/workflows/pytest-darwin.yaml.disabled
- .github/workflows/pytest-linux.yaml
- .github/workflows/pytest-windows.yaml
- .github/workflows/python-code-quality.yaml
- .github/workflows/unittest-examples-linux.yaml
- .github/workflows/unittest-linux.yaml
Issue number: senzing-factory/build-resources#69
> senzing-factory/build-resources#69 add linting

- .github/workflows/bandit.yaml
- .github/workflows/dependency-scan.yaml
> switch to fpvs

- .github/workflows/check-development-dependencies.yaml
- .github/workflows/mypy.yaml
- .mypy.ini
- Makefile
- development-requirements.txt
- src/senzing_grpc/szconfig.py
- src/senzing_grpc/szconfigmanager.py
- src/senzing_grpc/szdiagnostic.py
- src/senzing_grpc/szengine.py
- src/senzing_grpc/szproduct.py
- tests/szconfig_test.py
- tests/szconfigmanager_test.py
- tests/szdiagnostic_test.py
- tests/szengine_test.py
- tests/szproduct_test.py
> 67 dockter 1

- CHANGELOG.md
- README.md
- requirements.txt
- setup.cfg
> #85 Add help

- setup.cfg
> #99 Bump package version

- setup.cfg
> #85 Update package version

- CHANGELOG.md
- requirements.txt
- setup.cfg
- src/senzing_grpc/szconfig.py
- src/senzing_grpc/szconfigmanager.py
- src/senzing_grpc/szengine.py
- tests/szconfig_test.py
> #142 Fix signature

- CHANGELOG.md
- examples/szengine/find_network_by_entity_id.py
- examples/szengine/find_network_by_record_id.py
> #135 Update BUILD_OUT_DEGREES

- CHANGELOG.md
- pyproject.toml
- setup.cfg
- src/senzing_grpc/szabstractfactory.py
- src/senzing_grpc/szconfig.py
- src/senzing_grpc/szconfigmanager.py
- src/senzing_grpc/szdiagnostic.py
- src/senzing_grpc/szengine.py
- src/senzing_grpc/szproduct.py
> #168 Remove kwargs

- .github/workflows/bandit.yaml
- .github/workflows/build-distribution.yaml
- .github/workflows/check-development-dependencies.yaml
- .github/workflows/create-sphinx-documentation.yaml
- .github/workflows/isort.yaml
- .github/workflows/publish-to-pypi.yaml
> update python versions

- src/senzing_grpc/szabstractfactory.py
- src/senzing_grpc/szconfig.py
- src/senzing_grpc/szconfigmanager.py
- src/senzing_grpc/szdiagnostic.py
- src/senzing_grpc/szengine.py
- src/senzing_grpc/szhelpers.py
- src/senzing_grpc/szproduct.py
> #192 Move to Grpc suffix

- CHANGELOG.md
- tests/szengine_test.py
> #203 Improve test cases

- src/senzing_grpc/szconfig.py
- tests/szconfig_test.py
> #201 remove as_str

- .github/workflows/pytest-darwin.yaml
- .github/workflows/pytest-linux-tls-server-side.yaml
- .github/workflows/pytest-linux.yaml
- .github/workflows/pytest-windows.yaml
> #232 Refactor to template-python

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
- .github/workflows/bandit.yaml
- .github/workflows/black.yaml
- .github/workflows/build-distribution.yaml
- .github/workflows/check-development-dependencies.yaml
- .github/workflows/create-sphinx-documentation.yaml
- .github/workflows/flake8.yaml
- .github/workflows/isort.yaml
- .github/workflows/mypy.yaml
- .github/workflows/publish-to-pypi.yaml
- .github/workflows/pylint.yaml
- .github/workflows/pytest-linux.yaml
Issue number: senzing-factory/build-resources#179
> senzing-factory/build-resources#179 add slack notifications

- .github/workflows/bearer.yaml
> #256 add bearer

- documentation-requirements.txt
> #316 downgrade sphinx-tabs for conflict

- documentation-requirements.txt
> #325 unpin sphinx tabs patch version
